### PR TITLE
Fixes connect() bug, crash bug, I/O error bug, and more.

### PR DESCRIPTION
**Pull request by alrvid**
1. Fixes USB thumb drive remove and insert again bug
2. Fixes crash on mount() before connect() bug
3. Fixes incorrect comment about stall handling
4. Fixes I/O errors when writing to some USB thumb drive models
5. Fixes incorrectly named constant (MAX_NYET_RETRY to MAX_NOTREADY_RETRY)
6. Improves the source code comments in several locations

### CODE REVIEW

**Comment by alrvid** [comment]
The Spell Check failure is because a comment correctly contains the word "unstall" - as in clearing the halted feature of the USB EPs when receiving a stall. It's _not_ supposed to be "uninstall" even though that would satisfy Spell Check.

**Review by per1234 — CHANGES_REQUESTED** [review]
> The Spell Check failure is because a comment correctly contains the word "unstall"

Please add the word that is producing the false spell check positive to the `ignore-words-list` field of the `.codespellrc` configuration file:

https://github.com/arduino-libraries/Arduino_USBHostMbed5/blob/d8287c34cbdad295e514d8975b599b139bbde2b0/.codespellrc#L5

**Review by per1234 — COMMENTED** [review]
Changes to [**codespell**](https://github.com/codespell-project/codespell) configuration are perfect. I'm not able to evaluate the changes to the library codebase.

Thanks @alrvid!

**Comment by facchinm** [comment]
Lovely work, thanks a lot!

**Pull request merged**
